-- SBI is intentionally isolated from the existing BOB production tables.
-- This migration only creates new SBI-prefixed objects; it does not alter,
-- update, delete, or copy any existing BOB data.

create table if not exists public.sbi_executives (
  id uuid primary key default gen_random_uuid(),
  executive_code text not null unique check (executive_code ~ '^SBI[0-9]{3,}$'),
  full_name text not null,
  mobile text,
  area text,
  vehicle_type text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sbi_cases (
  id uuid primary key default gen_random_uuid(),
  sn integer,
  case_type text,
  alpha text,
  sol_id text,
  account_number text not null unique,
  account_name text not null,
  customer_id text,
  sanction_limit numeric not null default 0,
  sanction_date date,
  scheme_code text,
  rev_seg text,
  customer_balance numeric not null default 0,
  balance_inr numeric not null default 0,
  ecgc_receivable numeric not null default 0,
  asset_class text,
  npa_date date,
  two text,
  fraud text,
  total_provision numeric not null default 0,
  branch text,
  address text,
  mobile_number text,
  village text,
  bank_name text not null default 'State Bank of India (SBI)',
  status text not null default 'pending',
  assigned_executive_id uuid references public.sbi_executives(id) on delete set null,
  assigned_executive text,
  executive_code text,
  remarks text,
  source_file text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sbi_payments (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.sbi_cases(id) on delete restrict,
  executive_id uuid references public.sbi_executives(id) on delete set null,
  amount numeric not null check (amount > 0),
  payment_mode text,
  reference_number text,
  receipt_number text,
  remarks text,
  payment_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.sbi_field_visits (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.sbi_cases(id) on delete restrict,
  executive_id uuid references public.sbi_executives(id) on delete set null,
  photo_path text,
  latitude double precision,
  longitude double precision,
  outcome text,
  remarks text,
  next_follow_up date,
  captured_at timestamptz not null default now()
);

create table if not exists public.sbi_followups (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.sbi_cases(id) on delete cascade,
  executive_id uuid references public.sbi_executives(id) on delete set null,
  followup_date date not null,
  status text not null default 'pending',
  remarks text,
  created_at timestamptz not null default now()
);

create table if not exists public.sbi_gps_locations (
  id bigint generated by default as identity primary key,
  executive_id uuid not null references public.sbi_executives(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists sbi_cases_executive_idx on public.sbi_cases(assigned_executive_id);
create index if not exists sbi_payments_case_idx on public.sbi_payments(case_id);
create index if not exists sbi_visits_case_idx on public.sbi_field_visits(case_id);
create index if not exists sbi_followups_case_idx on public.sbi_followups(case_id);
create index if not exists sbi_gps_executive_time_idx on public.sbi_gps_locations(executive_id, recorded_at desc);

alter table public.sbi_executives enable row level security;
alter table public.sbi_cases enable row level security;
alter table public.sbi_payments enable row level security;
alter table public.sbi_field_visits enable row level security;
alter table public.sbi_followups enable row level security;
alter table public.sbi_gps_locations enable row level security;

-- No permissive policies are created here. Access remains closed until the
-- existing authentication roles and required SBI operations are reviewed.

create policy "authenticated admins manage sbi executives" on public.sbi_executives
  for all to authenticated using (true) with check (true);
create policy "authenticated admins manage sbi cases" on public.sbi_cases
  for all to authenticated using (true) with check (true);
create policy "authenticated admins manage sbi payments" on public.sbi_payments
  for all to authenticated using (true) with check (true);
create policy "authenticated admins manage sbi visits" on public.sbi_field_visits
  for all to authenticated using (true) with check (true);
create policy "authenticated admins manage sbi followups" on public.sbi_followups
  for all to authenticated using (true) with check (true);
create policy "authenticated admins manage sbi gps" on public.sbi_gps_locations
  for all to authenticated using (true) with check (true);

create or replace function public.sbi_register_executive(
  p_full_name text, p_mobile text, p_area text, p_vehicle_type text
) returns setof public.sbi_executives
language plpgsql security definer set search_path = public as $$
declare
  next_number integer;
  created public.sbi_executives;
begin
  if nullif(trim(p_full_name), '') is null or p_mobile !~ '^[0-9]{10,15}$'
     or nullif(trim(p_area), '') is null then
    raise exception 'Name, valid mobile aur area required hai';
  end if;
  if exists (select 1 from public.sbi_executives where mobile = p_mobile) then
    raise exception 'Is mobile number se registration pehle se maujood hai';
  end if;
  perform pg_advisory_xact_lock(hashtext('sbi_executive_code'));
  select coalesce(max(substring(executive_code from '[0-9]+$')::integer), 0) + 1
    into next_number from public.sbi_executives;
  insert into public.sbi_executives(executive_code, full_name, mobile, area, vehicle_type)
  values ('SBI' || lpad(next_number::text, 3, '0'), trim(p_full_name), p_mobile, trim(p_area), p_vehicle_type)
  returning * into created;
  return next created;
end $$;

create or replace function public.sbi_mobile_find_executive(
  p_id text default null, p_code text default null, p_mobile text default null
) returns setof public.sbi_executives
language sql security definer stable set search_path = public as $$
  select e.* from public.sbi_executives e
  where (p_id is not null and e.id::text = p_id)
     or (p_code is not null and p_mobile is not null
         and lower(e.executive_code) = lower(trim(p_code)) and e.mobile = p_mobile)
  limit 1
$$;

create or replace function public.sbi_mobile_executive_cases(
  p_executive_id text, p_executive_code text, p_mobile text
) returns setof public.sbi_cases
language sql security definer stable set search_path = public as $$
  select c.* from public.sbi_cases c
  join public.sbi_executives e on e.id::text = p_executive_id
  where e.status in ('active','approved','online')
    and lower(e.executive_code) = lower(trim(p_executive_code)) and e.mobile = p_mobile
    and (c.assigned_executive_id = e.id or lower(c.executive_code) = lower(e.executive_code))
  order by c.created_at desc
$$;

create or replace function public.sbi_mobile_update_case_status(
  p_case_id text, p_executive_id text, p_executive_code text, p_mobile text, p_status text
) returns boolean language plpgsql security definer set search_path = public as $$
begin
  update public.sbi_cases c set status = p_status, updated_at = now()
  from public.sbi_executives e
  where c.id::text = p_case_id and e.id::text = p_executive_id
    and lower(e.executive_code) = lower(trim(p_executive_code)) and e.mobile = p_mobile
    and (c.assigned_executive_id = e.id or lower(c.executive_code) = lower(e.executive_code));
  return found;
end $$;

create or replace function public.sbi_mobile_executive_payments(
  p_executive_id text, p_executive_code text, p_mobile text
) returns setof public.sbi_payments
language sql security definer stable set search_path = public as $$
  select p.* from public.sbi_payments p
  join public.sbi_executives e on e.id = p.executive_id
  where e.id::text = p_executive_id
    and lower(e.executive_code) = lower(trim(p_executive_code)) and e.mobile = p_mobile
  order by p.created_at desc
$$;

create or replace function public.sbi_mobile_record_payment(
  p_case_id text, p_executive_id text, p_executive_code text, p_mobile text,
  p_amount numeric, p_payment_mode text, p_reference_number text,
  p_receipt_number text, p_remarks text, p_payment_date date
) returns uuid language plpgsql security definer set search_path = public as $$
declare created_id uuid;
begin
  if p_amount <= 0 then raise exception 'Payment amount invalid hai'; end if;
  insert into public.sbi_payments(case_id, executive_id, amount, payment_mode,
    reference_number, receipt_number, remarks, payment_date)
  select c.id, e.id, p_amount, p_payment_mode, p_reference_number,
    p_receipt_number, p_remarks, p_payment_date
  from public.sbi_cases c join public.sbi_executives e on e.id::text = p_executive_id
  where c.id::text = p_case_id and lower(e.executive_code) = lower(trim(p_executive_code))
    and e.mobile = p_mobile and (c.assigned_executive_id = e.id or lower(c.executive_code) = lower(e.executive_code))
  returning id into created_id;
  if created_id is null then raise exception 'Case SBI executive ko assigned nahi hai'; end if;
  return created_id;
end $$;

create or replace function public.sbi_mobile_save_gps_location(
  p_executive_id text, p_executive_code text, p_mobile text, p_latitude double precision,
  p_longitude double precision, p_accuracy double precision, p_recorded_at timestamptz
) returns bigint language plpgsql security definer set search_path = public as $$
declare created_id bigint;
begin
  insert into public.sbi_gps_locations(executive_id, latitude, longitude, accuracy, recorded_at)
  select e.id, p_latitude, p_longitude, p_accuracy, p_recorded_at from public.sbi_executives e
  where e.id::text = p_executive_id and lower(e.executive_code) = lower(trim(p_executive_code)) and e.mobile = p_mobile
  returning id into created_id;
  return created_id;
end $$;

create or replace function public.sbi_mobile_record_detailed_visit(
  p_case_id text, p_executive_id text, p_executive_code text, p_mobile text,
  p_photo_path text, p_latitude double precision, p_longitude double precision,
  p_outcome text, p_remarks text, p_next_follow_up date
) returns uuid language plpgsql security definer set search_path = public as $$
declare created_id uuid;
begin
  insert into public.sbi_field_visits(case_id, executive_id, photo_path, latitude,
    longitude, outcome, remarks, next_follow_up)
  select c.id, e.id, p_photo_path, p_latitude, p_longitude, p_outcome, p_remarks, p_next_follow_up
  from public.sbi_cases c join public.sbi_executives e on e.id::text = p_executive_id
  where c.id::text = p_case_id and lower(e.executive_code) = lower(trim(p_executive_code))
    and e.mobile = p_mobile and (c.assigned_executive_id = e.id or lower(c.executive_code) = lower(e.executive_code))
  returning id into created_id;
  if created_id is null then raise exception 'Case SBI executive ko assigned nahi hai'; end if;
  update public.sbi_cases set status = 'Visited', updated_at = now() where id::text = p_case_id;
  return created_id;
end $$;

revoke all on function public.sbi_register_executive(text,text,text,text) from public;
grant execute on function public.sbi_register_executive(text,text,text,text) to anon, authenticated;
grant execute on function public.sbi_mobile_find_executive(text,text,text) to anon, authenticated;
grant execute on function public.sbi_mobile_executive_cases(text,text,text) to anon, authenticated;
grant execute on function public.sbi_mobile_update_case_status(text,text,text,text,text) to anon, authenticated;
grant execute on function public.sbi_mobile_executive_payments(text,text,text) to anon, authenticated;
grant execute on function public.sbi_mobile_record_payment(text,text,text,text,numeric,text,text,text,text,date) to anon, authenticated;
grant execute on function public.sbi_mobile_save_gps_location(text,text,text,double precision,double precision,double precision,timestamptz) to anon, authenticated;
grant execute on function public.sbi_mobile_record_detailed_visit(text,text,text,text,text,double precision,double precision,text,text,date) to anon, authenticated;

insert into storage.buckets(id, name, public)
values ('sbi-visit-photos', 'sbi-visit-photos', false)
on conflict (id) do nothing;

create policy "SBI app uploads visit photos" on storage.objects
  for insert to anon, authenticated with check (bucket_id = 'sbi-visit-photos');
create policy "authenticated admins view SBI visit photos" on storage.objects
  for select to authenticated using (bucket_id = 'sbi-visit-photos');
